# Generated by Django 4.2.4 on 2023-11-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
