# Generated by Django 4.2.4 on 2023-08-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
    ]
