# Generated by Django 4.2.4 on 2023-08-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_cliente_created_at_cliente_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="apellido",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
