# Generated by Django 4.2.4 on 2023-09-21 05:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_alter_cliente_apellido_alter_cliente_direccion_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={
                "ordering": ["id"],
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.AlterModelOptions(
            name="factura",
            options={
                "ordering": ["id"],
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
            },
        ),
    ]
