# Generated by Django 4.2.4 on 2023-10-05 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0007_alter_sede_company"),
        ("sales", "0005_alter_cliente_options_alter_factura_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="cliente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="funcionario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="sede",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.sede",
            ),
        ),
    ]
