# Generated by Django 4.2.4 on 2023-08-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_realizado", models.DateTimeField(blank=True, null=True)),
                ("fecha_llegada", models.DateTimeField(blank=True, null=True)),
                ("estado", models.BooleanField(default=False)),
                ("total", models.FloatField(verbose_name="Total de el pedido")),
            ],
        ),
        migrations.CreateModel(
            name="through_infoPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.CharField(max_length=255)),
                ("precio_unitario", models.CharField(max_length=255)),
                (
                    "pedido",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supply.pedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.CharField(max_length=255)),
                ("telefono", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("sede", models.ManyToManyField(to="company.sede")),
            ],
        ),
    ]
