# Generated by Django 4.2.4 on 2023-09-21 05:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0005_alter_through_infopedido_cantidad_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pedido",
            options={
                "ordering": ["id"],
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
            },
        ),
        migrations.AlterModelOptions(
            name="proveedor",
            options={
                "ordering": ["id"],
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
            },
        ),
        migrations.AlterModelOptions(
            name="through_infopedido",
            options={
                "ordering": ["id"],
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
    ]
