# Generated by Django 4.2.4 on 2023-09-23 15:50

import apps.supply.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0006_alter_pedido_options_alter_proveedor_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="imagen",
            field=models.ImageField(
                null=True, upload_to=apps.supply.models.upload_to_proveedor
            ),
        ),
    ]
