# Generated by Django 4.2.4 on 2023-10-05 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0015_alter_categoria_company_alter_producto_categoria_and_more"),
        ("company", "0007_alter_sede_company"),
        ("supply", "0007_alter_proveedor_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="funcionario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="proveedor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="supply.proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="sede",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.sede",
            ),
        ),
        migrations.AlterField(
            model_name="through_infopedido",
            name="pedido",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="supply.pedido",
            ),
        ),
        migrations.AlterField(
            model_name="through_infopedido",
            name="producto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.producto",
            ),
        ),
    ]
