# Generated by Django 4.2.4 on 2023-10-31 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0008_alter_pedido_funcionario_alter_pedido_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='through_infopedido',
            options={'ordering': ['id'], 'verbose_name': 'Producto pedido', 'verbose_name_plural': 'Productos pedidos'},
        ),
    ]
