# Generated by Django 4.2.4 on 2023-08-21 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_funcionario_options_funcionario_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funcionario",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
    ]
