# Generated by Django 4.2.4 on 2023-09-23 15:18

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_funcionario_options_alter_funcionario_cargo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="imagen",
            field=models.ImageField(
                null=True, upload_to=apps.user.models.upload_to_user
            ),
        ),
    ]
