# Generated by Django 4.2.4 on 2023-08-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Fecha de eliminación",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "Logo",
                    models.ImageField(
                        upload_to="media/", verbose_name="Logo de la compañia"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Fecha de eliminación",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.CharField(max_length=255)),
                ("ciudad", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
