# Generated by Django 4.2.4 on 2023-09-21 05:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_alter_company_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["id"],
                "verbose_name": "Compañia",
                "verbose_name_plural": "Compañia",
            },
        ),
        migrations.AlterModelOptions(
            name="sede",
            options={
                "ordering": ["id"],
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
            },
        ),
    ]
