# Generated by Django 4.2.4 on 2023-09-24 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0005_alter_company_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="Logo",
            new_name="logo",
        ),
    ]
