# Generated by Django 4.2.4 on 2023-11-09 00:51

import apps.catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(null=True)),
                ('tipo', models.CharField(choices=[('servicio', 'servicio'), ('producto', 'producto'), ('activo', 'activo')], default='producto', max_length=20)),
                ('color', models.CharField(max_length=20, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación')),
                ('imagen', models.ImageField(null=True, upload_to=apps.catalog.models.upload_to_producto)),
                ('nombre', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('precio', models.FloatField()),
                ('codigo', models.CharField(max_length=20, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Through_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación')),
                ('stock', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.producto')),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.sede')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.categoria')),
                ('sedes', models.ManyToManyField(to='company.sede')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='sedes',
            field=models.ManyToManyField(related_name='productos', through='catalog.Through_stock', to='company.sede'),
        ),
    ]
