# Generated by Django 4.2.4 on 2023-08-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
        ("catalog", "0002_categoria_created_at_categoria_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="sede",
        ),
        migrations.AddField(
            model_name="producto",
            name="sedes",
            field=models.ManyToManyField(
                through="catalog.Through_stock", to="company.sede"
            ),
        ),
        migrations.AlterField(
            model_name="through_stock",
            name="stock",
            field=models.IntegerField(),
        ),
    ]
