# Generated by Django 4.2.4 on 2023-08-20 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_sede_company"),
        ("catalog", "0003_remove_producto_sede_producto_sedes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="sedes",
            field=models.ManyToManyField(
                related_name="productos",
                through="catalog.Through_stock",
                to="company.sede",
            ),
        ),
    ]
