# Generated by Django 4.2.4 on 2023-08-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_categoria_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="through_stock",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
