# Generated by Django 4.2.4 on 2023-08-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_producto_descripcion_alter_through_stock_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="descripcion",
            field=models.TextField(null=True),
        ),
    ]
