# Generated by Django 4.2.4 on 2023-08-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_alter_categoria_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="codigo",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
