# Generated by Django 4.2.4 on 2023-08-20 03:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_producto_codigo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="Categoria",
            new_name="categoria",
        ),
    ]
