# Generated by Django 4.2.4 on 2023-08-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_alter_company_logo"),
        ("catalog", "0009_rename_categoria_producto_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="sedes",
            field=models.ManyToManyField(to="company.sede"),
        ),
    ]
