# Generated by Django 4.2.4 on 2023-09-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_rename_categoria_servicio_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="marca",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
