# Generated by Django 4.2.4 on 2023-09-23 15:50

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_alter_categoria_options_alter_producto_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                null=True, upload_to=apps.catalog.models.upload_to_producto
            ),
        ),
    ]
