# Generated by Django 4.2.4 on 2023-10-05 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0007_alter_sede_company"),
        ("catalog", "0014_producto_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="through_stock",
            name="producto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.producto",
            ),
        ),
        migrations.AlterField(
            model_name="through_stock",
            name="sede",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.sede",
            ),
        ),
    ]
